### ISSUE TITLE
Activer dependabot

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/opt-temps-attente-agences-api#11]

**Comment by Dougniel** [comment]
@adriens, j'ai reproduit le problème que j'ai eu sur dependabot et cette fois-si j'ai juste enlevé l'espace dans `<relativePath />` (pour que ça devienne <relativePath/>) et là plus de problèmes ! C'est pour cela que ça fonctionnait sur opt-nc/consumer-sirh !

**Comment by adriens** [comment]
Top !
