### ISSUE TITLE
Mise en place de release-semantic

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/opt-temps-attente-agences-api#12]

**Comment by Dougniel** [comment]
@adriens, pourrais tu activer la branche `main` comme branche par défaut dans les [settings du projet stp](https://github.com/opt-nc/opt-temps-attente-agences-api/settings) ?

ça permet d'homogénéiser avec les autres projets

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/142786424-9d1df392-0546-47ee-982e-434df5afde64.png)

**Comment by adriens** [comment]
> pourrais tu activer la branche main comme branche par défaut 

fait ;-p

**Comment by adriens** [comment]
👏
