### ISSUE TITLE
Support position geo

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/opt-temps-attente-agences-api#2]

**Comment by Dougniel** [comment]
@adriens , il y a une histoire de droits à voir et je n'ai pas accès aux paramètres. Il faut que ce repo puisse avoir accès au repo maven de github du sdk

**Comment by adriens** [comment]
tu es déja maintainer, je ne peux pas te mettre owner, cela n'a pas de sens. On ne doit pas avoir besoin d'être owner pour pousser une release.
