### ISSUE TITLE
🚨 Mauvais port sur l'image Docker ⚡ 

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-temps-attente-agences-api#22]
# 👉 Description

Actuellement le port documenté et configuré est le `8081` tandis que pour tous les autres projets du même type c'est `8080`. Pour nous simplifier la vie, il convient d'être consistants, surotut désormais que nous déployons sur AWS : nos collègues du SEP doivent être à l'aise et ne pas se poser de questions.

![image](https://user-images.githubusercontent.com/5235127/144931229-614eee47-5d23-4d82-a254-f579c0461bed.png)

# 👇  Actions

- [x] Modifier le port par défaut à `8080`
- [ ] Répercuter ce changement dans les docs (`README.md` et page sur `Dockehub`)
- [ ] Releaser une nouvelle version

**Comment by adriens** [comment]
reste màj ds docs et release 💪

**Comment by Dougniel** [comment]
@adriens, Bon, il reste un petit soucis, l'image docker a bien été taggé en `stable`et `latest`mais pas avec le numéro de version, je regarde

**Comment by adriens** [comment]
O, oublie pas la doc sur la page DockerHub quo est tjs en `8081` 😸 

J'atends ton GO de tte façon pour lancer le ticket Jira de déploiement

**Comment by adriens** [comment]
Ok c'est reparti pour #20
