### ISSUE TITLE
💣 URGENT > Image non fonctionnelle : connection refused🚨 

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-temps-attente-agences-api#27]
# 👉 Contexte

L'image a été déployée sur fargate mais ne répond pas. Cette demande bloque #20 , le déploiement sur le marketplace d'API.

# 📑 Reproduire le dysfonctionnement

Pour reproduire le dysfonctionnement : 

- Aller sur une session vierge katacoda : https://www.katacoda.com/courses/ubuntu/playground
- Démarrer l'API et installer quelques outils :

```
# Install d'outils
sudo apt-get install httpie jq -y
# Démarrer l'image tel que demandé pour Fargate
docker run -d --rm -p 8080:8080 optnc/opt-temps-attente-agences-api:stable
```

👇 Puis constater le dysfonctionnement : 

```
http http://localhost:8080/temps-attente/agence/4161
http http://localhost:8080/communes
```

répond `connection refused` : 

```
http: error: ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /temps-attente/agence/4161 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff16924b70>: Failed to establish a new connection: [Errno 111] Connection refused',)) while doing GET request to URL: http://localhost:8080/temps-attente/agence/4161
```
# Conséquences

- Cela bloque #20

# 💡 Pistes

Je me demande si cela n'est pas lié à la modification du port qui doit être `8080`

**Comment by adriens** [comment]
Je tente un build & run local depuis les sources via mvn pour voi

**Comment by Dougniel** [comment]
@adriens , pour l'instant je ne reproduis pas

**Comment by adriens** [comment]
Idem en local depuis les sources

![image](https://user-images.githubusercontent.com/5235127/146267021-79931174-de92-4699-a94e-ebbd7c1b8221.png)

**Comment by Dougniel** [comment]
Tu as les logs du service ?

**Comment by adriens** [comment]
Je l'ai joué sur un playground tout con sur Katacoda pour etre propre, je vais compltéer l'issue dans ce sens

**Comment by adriens** [comment]
tu peux aller sur https://www.katacoda.com/courses/kubernetes/playground et passer les commandes

**Comment by adriens** [comment]
ca fait exacetemnt pareil sur Fargate : 

![image](https://user-images.githubusercontent.com/5235127/146267877-b76ca0a6-95a4-427c-a157-12473caf5efb.png)

**Comment by adriens** [comment]
Genre ça démarre mais c pas accessible 🤔

**Comment by Dougniel** [comment]
GET /communes n'existe pas

**Comment by adriens** [comment]
Autres exemples d'appel : 

```
sudo apt-get install httpie jq -y
http http://127.0.0.1:8080/temps-attente/agence/4161
http http://127.0.0.1:8080/temps-attente/agence/4161 | jq '.idAgence'
http http://127.0.0.1:8080/temps-attente/agences # Accès à la liste des agences
http 'http://127.0.0.1:8080/temps-attente/agences?lon=166.4260482788086&lat=-22.25097078275085&distanceInMeters=3000' # Accès à la liste des communes par distance
http http://127.0.0.1:8080/temps-attente/agences/noumea # Accès à la liste des agences de Nouméa
```

**Comment by Dougniel** [comment]
De mon côté mnv spring-boot:run passe bien sur la head depuis le browser : 
![image](https://user-images.githubusercontent.com/39691264/146268882-c6b1bac5-3e3d-4f06-a6be-9c4403bf8ef2.png)

**Comment by adriens** [comment]
Euhhhh, tu me parles de partenaires là..

**Comment by adriens** [comment]
T'es pas sur la bonne image

**Comment by Dougniel** [comment]
Je me suis trompé, j'ai lancé en mvn api-partenaires :smile: 
Le réveil est difficile ce matin...

En effet /communes existe

**Comment by Dougniel** [comment]
Bref, que ce soit sous docker ou bien en mvn ça fonctionne sur mon poste :
![image](https://user-images.githubusercontent.com/39691264/146269615-e903132a-7ea6-4558-99a5-d837c8fb75d0.png)
![image](https://user-images.githubusercontent.com/39691264/146269871-c48e6d6d-0f51-4af4-a48a-d7dab144a4d0.png)

**Comment by adriens** [comment]
ca coince sur fargate et Katacoda, pour les mêmes raisons : `connection refused`

rejoue le truc sur Katacoda 🙏 pour voir

**Comment by adriens** [comment]
(je suis sur `stable`)

**Comment by Dougniel** [comment]
J'ai pas compris le katacoda, les 2 terminaux sont sur des noeuds différents

**Comment by adriens** [comment]
j'ai basculé la commande docker en daemon, comme ça tu peux tout tourner sur le même noeud

**Comment by adriens** [comment]
...dans le même terminal

**Comment by Dougniel** [comment]
@adriens, si sur katacoda je lance tout sur le même terminal ça fonctionne, le problème ne viens pas de l'image à priori

**Comment by adriens** [comment]
Sinon, bascule sur celui-ci https://www.katacoda.com/courses/ubuntu/playground

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/146270825-b0c4be46-849e-45d4-ba55-4f1b8a63030f.png)

```
$ http http://localhost:8080/temps-attente/agence/4161

http: error: ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /temps-attente/agence/4161 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f2327d21190>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by Dougniel** [comment]
Tu pourrais faire un docker ps ? Je crois que c'est dans les lignes de commande qu'il y à un soucis

**Comment by Dougniel** [comment]
@adriens , c'est le copier coller sur katacoda qui foire, ça ne lance simplement par l'image docker

**Comment by adriens** [comment]
Démarre l'image, je l'ai déja démarrée l'image ça pull et ça boot

**Comment by Dougniel** [comment]
@adriens quand je prends je lance le docker run directement ça fonctionne oui, donc pas de soucis :smile: 
![image](https://user-images.githubusercontent.com/39691264/146271735-7939fcea-8e8d-4b47-9675-ce3161e360e4.png)

**Comment by adriens** [comment]
Mauvaise url copiée...
Tout marche.
![image](https://user-images.githubusercontent.com/5235127/146275178-c9ca7404-b894-49a0-9441-a20c08ce1014.png)
