### ISSUE TITLE
Image Knative

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/opt-temps-attente-agences-api#3]

**Comment by Dougniel** [comment]
Je galère avec le certificat root CA de l'OPT : 
- j'ai eu un premier soucis x509 lors de la provision d'un service (`ka service create ..`) : 
  ````
  error: Internal error occurred: failed calling webhook "webhook.serving.knative.dev": Post "https://webhook.knative- 
  serving.svc:443/?timeout=10s": dial tcp 10.96.39.225:443: connect: connection refused
  ````
  J'ai résolu en installant les certificats OPT dans le container de knative (`knative-control-plane`) qui tourne sous Ubuntu en suivant [la procédure classique ](https://askubuntu.com/a/94861)
- maintenant j'ai un autre soucis, semble t'il au téléchargement de l'image : 
  ```bash
  kn service create opt-temps-attente-agences-api --image docker.io/optnc/opt-temps-attente-agences-api --env TARGET="Temps attente 2.0-SNAPSHOT"
  Creating service 'opt-temps-attente-agences-api' in namespace 'default':
  
    0.033s The Route is still working to reflect the latest desired specification.
    0.055s Configuration "opt-temps-attente-agences-api" is waiting for a Revision to become ready.
    0.067s ...
    5.594s Revision "opt-temps-attente-agences-api-00001" failed with message: Unable to fetch image "docker.io/optnc/opt-temps-attente-agences-api": failed to resolve image to digest: Get "https://index.docker.io/v2/": x509: certificate signed by unknown authority.
    5.627s Configuration "opt-temps-attente-agences-api" does not have any ready Revision.
  Error: RevisionFailed: Revision "opt-temps-attente-agences-api-00001" failed with message: Unable to fetch image "docker.io/optnc/opt-temps-attente-agences-api": failed to resolve image to digest: Get "https://index.docker.io/v2/": x509: certificate signed by unknown authority.
  Run 'kn --help' for usage
  ```
  Et là je galère

**Comment by Dougniel** [comment]
J'ai eu une discussion avec Samuel à ce sujet, j'ai fait une [demande pour exclure les registry Docker du filtrage HTTPS](https://jira.intranet.opt/browse/RX-4599)

**Comment by Dougniel** [comment]
Depuis mon poste ça fonctionne mieux :ok: 

Le passage à Knative se fait très facilement car il n'y à pas de changements dans l'image docker  après avoir installé le [runtime Knative en mde dev](https://knative.dev/docs/getting-started/), le lancement se fait via un `kubectl` et un fichier de déploiement spécialisé, soit une commande `kn` qui fait tout. J'ai mis à jour le README.md.

Petite remarque au passage : le runtime Knative `knative-control-plane`utilise environ 30% du CPU en idle et 10% de la RAM (observé sur mon poste perso et le poste OPT), c'est dommage mais c'est peut-être différent en version prod

@adriens, est-ce que ça te va ? Si ce n'est pas le cas ré-ouvre le ticket :call_me_hand:

**Comment by adriens** [comment]
Super boulot @Dougniel , mais 

> environ 30% du CPU en idle

Ca c'est pas très engageant, c suspect même 😆

**Comment by adriens** [comment]
YES en effet, super boulot https://github.com/opt-nc/opt-temps-attente-agences-api#lancenment-via-knative

**Comment by adriens** [comment]
Ticket DEVOPS-LABS créé, on posera le sujet prochainement, pour que ça tienne au format DEVOPS-LABS
