### ISSUE TITLE
📦 Packager en image native 🚀 

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-temps-attente-agences-api#42]

**Comment by adriens** [comment]
Cette API va connaître u nfort gain de popularité car nous allons commuqiuer sur cette API au niveau de l'office 👏

**Comment by adriens** [comment]
je bascule donc cette issue en `TODO`

**Comment by Dougniel** [comment]
Sur mon poste le démarrage passe de 10s à 1s 👍

**Comment by adriens** [comment]
Il faut qu'on puisse montrer ça, je prépare https://github.com/opt-nc/opt-temps-attente-agences-api/issues/52

**Comment by adriens** [comment]
YES ❣️
