### ISSUE TITLE
🎥 Démo video image Native sur Mac (M1) avec Docker (noK8S)👀 

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-temps-attente-agences-api#52]
# 👉 Contexte

L'API dispose désormais d'une image docker native (cf #42), il est donc intéressant de voir ce que cela change pour les intégrateurs de cette API... et pour cela rien de mieux qu'une courte démo video.

# 👇 Actions

Le but est donc de préparer une video sur Mac M1 qiu met en valeur un **scénario from scratch.**

**Sur l'image normale puis sur l'image native** : 

0. Via command line, afficher les infos système de la machine

1. Pull de l'mage
2. Boot de l'image via `docker`
3. Requête `httpie` avec la balise de chrono méta

Métriques à consigner et mettre en valeur lors de cette mini-démo : 

| Type image  | Pull time (s.)      |    Taille image (Mo) | Boot time (ms.) | Empreinte mémoire (Mo.)  | Temps de réponse (ms.)  |
| ------------- | ----------------- | --------------------- | ----------------- | ----------------------------- | -------------------------- |
| Normale      |  X                       |  X                            | X                        | X                                         | X                                     |
| Native         |  X                       |  X                             | X                       | X                                          | X                                     |

Me dropper la video par un moyen tiers comme d'habitude afin que je puisse la traiter et l'intégrer en vue de production de comm' et intégration à la chaîne YT.

**Comment by Dougniel** [comment]
@adriens, comme évoqué lors de la réunion, avec mon poste il y a un comportement anormal avec nos images Docker Java en non-natif qui mettent beaucoup plus de temps à démarrer (quand elles ne bloquent pas avant d'avoir démarré), du coup cette démo serait biaise, ce serait limite un facteur x20 qui n'est pas réaliste

Comme vu en daily, je ferme donc ce ticket car on a déjà le scénario [Katacoda SpringNative](https://www.katacoda.com/opt-labs/courses/partenaires-mobilis/springnative) qui met en évidences des résultats similaires et qui lui ait beaucoup plus réaliste

**Comment by adriens** [comment]
👍
