### ISSUE TITLE
Requête httpie à simplifier

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-temps-attente-agences-api#55]
Actuellement dans le README on a ceci : 

```
http 'http://127.0.0.1:8080/temps-attente/agences?lon=166.4260482788086&lat=-22.25097078275085&distanceInMeters=3000' # Accès à la liste des communes par distance
```

Simplifier en : 

- [x] éliminant `http://127.0.0.1`
- [x] sortant les paramètres de la requête de l'url et les passer dans la commande `httpie`
- [x] Mettre à jour le `md` de la page DockerHub

**Comment by adriens** [comment]
cf #54

**Comment by Dougniel** [comment]
a149be823e991fbdb44a9b7893bee17d990e3442

**Comment by adriens** [comment]
👍
