### ISSUE TITLE
Configurer le Code Scanning

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/opt-temps-attente-agences-api#60]
https://docs.github.com/en/code-security/secure-coding/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning

**Comment by Dougniel** [comment]
C'était déjà fait :
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/39691264/160846482-57fca907-9e0d-49ab-8189-96b79cca9d47.png">

**Comment by adriens** [comment]
:ok:
