### ISSUE TITLE
Ajouter lien portail rapidAPI en badge et doc sur le README

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-temps-attente-agences-api#61]
url : https://rapidapi.com/opt-nc-opt-nc-default/api/temps-attente-en-agence

**Comment by Dougniel** [comment]
Voici le résultat :
<img width="587" alt="image" src="https://user-images.githubusercontent.com/39691264/160781627-526e1f3f-3546-4c28-bcaf-9382ed3378bf.png">

En me basant sur cette doc https://docs.rapidapi.com/docs/optimize-your-website

**Comment by adriens** [comment]
Excellent !!! J'adore :heart_on_fire:

**Comment by adriens** [comment]
On va le généralise c vraiment excellent :muscle:
