### ISSUE TITLE
⚠️ CodeQL ne passe plus ⚠️ 

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/opt-temps-attente-agences-api#69]
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/39691264/163524621-cded506d-676f-4209-ba9e-4266a2e70b61.png">
Certainement liée au passage à Java 17 #42

**Comment by adriens** [comment]
:+1:

**Comment by adriens** [comment]
:clap:
