### ISSUE TITLE
🐳 Pas de description pour cette image 🐳 

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-temps-attente-agences-api#8]
# ❔Description

Actuellement cette image n'a pas de description courte : 

```
curl https://hub.docker.com/v2/repositories/optnc/opt-temps-attente-agences-api/ | jq .description
```
# ❕Conséquence

Cela nuit à sa bonne documentation et indexation.

# 👉Fix

- [x] Ajouter cette description : `API permettant d'interagir avec les noms de domaines en Nouvelle-Calédonie `

**Comment by Dougniel** [comment]
Oups, j'ai recopié bêtement la description et il y avait une erreur. J'ai mis ça `API REST des temps d'attente en agence OPT.nc`

**Comment by adriens** [comment]
Yep, c good !
![image](https://user-images.githubusercontent.com/5235127/133037743-86d0449c-d2c1-491d-9557-79be0ee910c3.png)

Merci @Dougniel
