### ISSUE TITLE
:shield: Your main branch isn't protected

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-temps-attente-agences-api#93]
![image](https://user-images.githubusercontent.com/5235127/179951210-1e05533d-683e-43fb-a518-a6bcef78ab8b.png)

**Comment by Dougniel** [comment]
<img width="787" alt="image" src="https://user-images.githubusercontent.com/39691264/180173254-2d0e6735-6840-45b6-8345-75d22eb5ab60.png">

**Comment by adriens** [comment]
:ok_man: :pray:
