### ISSUE TITLE
:world_map:  Code commune (code_officiel_geographique)

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-temps-attente-agences-api#96]
# :grey_question: Contexte

Sur chaque agence, vérfier que l'on dispose bien du `code_officiel_geographique` afin de pouvoir faire des jointures avec d'autres jeux de données tels que : 

- [Communes de la Nouvelle-Calédonie (limites communales terrestres simplifiées) ](https://data.gouv.nc/explore/dataset/communes-nc-limites-terrestres-simplifiees/information/)
- [Communes de la Nouvelle-Calédonie](https://data.gouv.nc/explore/dataset/communes-nc/information/)

# :dart: Action

- Pour chaque agence veiller à ce que l'on dispose du  `code_officiel_geographique`

**Comment by Dougniel** [comment]
@adriens, il n'y a pas de code commune mais il y a le code postal, du coup on peut faire la jointure avec ces sources de données

J'ai vérifié et le code postal est dans toutes les agences : 
<img width="632" alt="image" src="https://user-images.githubusercontent.com/39691264/187378718-58c9ecde-a8cc-491e-ad9f-8a56b8430a7d.png">

Je considère que c'est ok, si c'est pas bon, faut réouvrir

**Comment by adriens** [comment]
> [@adriens](https://github.com/adriens), il n'y a pas de code commune mais il y a le code postal, du coup on peut faire la jointure avec ces sources de données
> J'ai vérifié et le code postal est dans toutes les agences

C'est excellent ❣️
